package com.dsmjd.productutil.dto;

import java.util.Date;

public class PuSysUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.id
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.name
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.code
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.nickName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.userName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.phoneImg
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String phoneimg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.sex
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.birthday
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.idCard
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.censusType
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer censustype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.oldHome
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String oldhome;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.telephone
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.email
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.marriageState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer marriagestate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.address
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.homeAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String homeaddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.jobId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer jobid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.finishSchool
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String finishschool;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.speciality
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String speciality;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.diploma
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer diploma;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.finishSchoolDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date finishschooldate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.intoDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date intodate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.jobDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date jobdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.archivesAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String archivesaddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.descr
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String descr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.password
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.empState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer empstate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.userState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer userstate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.createTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.createrName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String creatername;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.updateTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.updaterName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String updatername;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.superAdmin
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer superadmin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.loginCount
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer logincount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.loginTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Date logintime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.loginIp
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String loginip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.parentId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer parentid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.roleId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.roleName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String rolename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.groupId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer groupid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.groupName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String groupname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.areaId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer areaid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.areaName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String areaname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.areaEasyName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String areaeasyname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.type
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.item1
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String item1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.item2
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String item2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.item3
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String item3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pu_sys_user.item4
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    private String item4;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.id
     *
     * @return the value of pu_sys_user.id
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.id
     *
     * @param id the value for pu_sys_user.id
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.name
     *
     * @return the value of pu_sys_user.name
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.name
     *
     * @param name the value for pu_sys_user.name
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.code
     *
     * @return the value of pu_sys_user.code
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.code
     *
     * @param code the value for pu_sys_user.code
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.nickName
     *
     * @return the value of pu_sys_user.nickName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.nickName
     *
     * @param nickname the value for pu_sys_user.nickName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.userName
     *
     * @return the value of pu_sys_user.userName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.userName
     *
     * @param username the value for pu_sys_user.userName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.phoneImg
     *
     * @return the value of pu_sys_user.phoneImg
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getPhoneimg() {
        return phoneimg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.phoneImg
     *
     * @param phoneimg the value for pu_sys_user.phoneImg
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setPhoneimg(String phoneimg) {
        this.phoneimg = phoneimg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.sex
     *
     * @return the value of pu_sys_user.sex
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.sex
     *
     * @param sex the value for pu_sys_user.sex
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.birthday
     *
     * @return the value of pu_sys_user.birthday
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.birthday
     *
     * @param birthday the value for pu_sys_user.birthday
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.idCard
     *
     * @return the value of pu_sys_user.idCard
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.idCard
     *
     * @param idcard the value for pu_sys_user.idCard
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.censusType
     *
     * @return the value of pu_sys_user.censusType
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getCensustype() {
        return censustype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.censusType
     *
     * @param censustype the value for pu_sys_user.censusType
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setCensustype(Integer censustype) {
        this.censustype = censustype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.oldHome
     *
     * @return the value of pu_sys_user.oldHome
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getOldhome() {
        return oldhome;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.oldHome
     *
     * @param oldhome the value for pu_sys_user.oldHome
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setOldhome(String oldhome) {
        this.oldhome = oldhome;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.telephone
     *
     * @return the value of pu_sys_user.telephone
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.telephone
     *
     * @param telephone the value for pu_sys_user.telephone
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.email
     *
     * @return the value of pu_sys_user.email
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.email
     *
     * @param email the value for pu_sys_user.email
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.marriageState
     *
     * @return the value of pu_sys_user.marriageState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getMarriagestate() {
        return marriagestate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.marriageState
     *
     * @param marriagestate the value for pu_sys_user.marriageState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setMarriagestate(Integer marriagestate) {
        this.marriagestate = marriagestate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.address
     *
     * @return the value of pu_sys_user.address
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.address
     *
     * @param address the value for pu_sys_user.address
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.homeAddress
     *
     * @return the value of pu_sys_user.homeAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getHomeaddress() {
        return homeaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.homeAddress
     *
     * @param homeaddress the value for pu_sys_user.homeAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setHomeaddress(String homeaddress) {
        this.homeaddress = homeaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.jobId
     *
     * @return the value of pu_sys_user.jobId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getJobid() {
        return jobid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.jobId
     *
     * @param jobid the value for pu_sys_user.jobId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.finishSchool
     *
     * @return the value of pu_sys_user.finishSchool
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getFinishschool() {
        return finishschool;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.finishSchool
     *
     * @param finishschool the value for pu_sys_user.finishSchool
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setFinishschool(String finishschool) {
        this.finishschool = finishschool;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.speciality
     *
     * @return the value of pu_sys_user.speciality
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.speciality
     *
     * @param speciality the value for pu_sys_user.speciality
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.diploma
     *
     * @return the value of pu_sys_user.diploma
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getDiploma() {
        return diploma;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.diploma
     *
     * @param diploma the value for pu_sys_user.diploma
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setDiploma(Integer diploma) {
        this.diploma = diploma;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.finishSchoolDate
     *
     * @return the value of pu_sys_user.finishSchoolDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getFinishschooldate() {
        return finishschooldate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.finishSchoolDate
     *
     * @param finishschooldate the value for pu_sys_user.finishSchoolDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setFinishschooldate(Date finishschooldate) {
        this.finishschooldate = finishschooldate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.intoDate
     *
     * @return the value of pu_sys_user.intoDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getIntodate() {
        return intodate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.intoDate
     *
     * @param intodate the value for pu_sys_user.intoDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setIntodate(Date intodate) {
        this.intodate = intodate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.jobDate
     *
     * @return the value of pu_sys_user.jobDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getJobdate() {
        return jobdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.jobDate
     *
     * @param jobdate the value for pu_sys_user.jobDate
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setJobdate(Date jobdate) {
        this.jobdate = jobdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.archivesAddress
     *
     * @return the value of pu_sys_user.archivesAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getArchivesaddress() {
        return archivesaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.archivesAddress
     *
     * @param archivesaddress the value for pu_sys_user.archivesAddress
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setArchivesaddress(String archivesaddress) {
        this.archivesaddress = archivesaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.descr
     *
     * @return the value of pu_sys_user.descr
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.descr
     *
     * @param descr the value for pu_sys_user.descr
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.password
     *
     * @return the value of pu_sys_user.password
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.password
     *
     * @param password the value for pu_sys_user.password
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.empState
     *
     * @return the value of pu_sys_user.empState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getEmpstate() {
        return empstate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.empState
     *
     * @param empstate the value for pu_sys_user.empState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setEmpstate(Integer empstate) {
        this.empstate = empstate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.userState
     *
     * @return the value of pu_sys_user.userState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.userState
     *
     * @param userstate the value for pu_sys_user.userState
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setUserstate(Integer userstate) {
        this.userstate = userstate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.createTime
     *
     * @return the value of pu_sys_user.createTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.createTime
     *
     * @param createtime the value for pu_sys_user.createTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.createrName
     *
     * @return the value of pu_sys_user.createrName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getCreatername() {
        return creatername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.createrName
     *
     * @param creatername the value for pu_sys_user.createrName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setCreatername(String creatername) {
        this.creatername = creatername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.updateTime
     *
     * @return the value of pu_sys_user.updateTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.updateTime
     *
     * @param updatetime the value for pu_sys_user.updateTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.updaterName
     *
     * @return the value of pu_sys_user.updaterName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getUpdatername() {
        return updatername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.updaterName
     *
     * @param updatername the value for pu_sys_user.updaterName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setUpdatername(String updatername) {
        this.updatername = updatername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.superAdmin
     *
     * @return the value of pu_sys_user.superAdmin
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getSuperadmin() {
        return superadmin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.superAdmin
     *
     * @param superadmin the value for pu_sys_user.superAdmin
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setSuperadmin(Integer superadmin) {
        this.superadmin = superadmin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.loginCount
     *
     * @return the value of pu_sys_user.loginCount
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.loginCount
     *
     * @param logincount the value for pu_sys_user.loginCount
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setLogincount(Integer logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.loginTime
     *
     * @return the value of pu_sys_user.loginTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.loginTime
     *
     * @param logintime the value for pu_sys_user.loginTime
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.loginIp
     *
     * @return the value of pu_sys_user.loginIp
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.loginIp
     *
     * @param loginip the value for pu_sys_user.loginIp
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.parentId
     *
     * @return the value of pu_sys_user.parentId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.parentId
     *
     * @param parentid the value for pu_sys_user.parentId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.roleId
     *
     * @return the value of pu_sys_user.roleId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.roleId
     *
     * @param roleid the value for pu_sys_user.roleId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.roleName
     *
     * @return the value of pu_sys_user.roleName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.roleName
     *
     * @param rolename the value for pu_sys_user.roleName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.groupId
     *
     * @return the value of pu_sys_user.groupId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.groupId
     *
     * @param groupid the value for pu_sys_user.groupId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.groupName
     *
     * @return the value of pu_sys_user.groupName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.groupName
     *
     * @param groupname the value for pu_sys_user.groupName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.areaId
     *
     * @return the value of pu_sys_user.areaId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.areaId
     *
     * @param areaid the value for pu_sys_user.areaId
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.areaName
     *
     * @return the value of pu_sys_user.areaName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.areaName
     *
     * @param areaname the value for pu_sys_user.areaName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.areaEasyName
     *
     * @return the value of pu_sys_user.areaEasyName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getAreaeasyname() {
        return areaeasyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.areaEasyName
     *
     * @param areaeasyname the value for pu_sys_user.areaEasyName
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setAreaeasyname(String areaeasyname) {
        this.areaeasyname = areaeasyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.type
     *
     * @return the value of pu_sys_user.type
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.type
     *
     * @param type the value for pu_sys_user.type
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.item1
     *
     * @return the value of pu_sys_user.item1
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getItem1() {
        return item1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.item1
     *
     * @param item1 the value for pu_sys_user.item1
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setItem1(String item1) {
        this.item1 = item1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.item2
     *
     * @return the value of pu_sys_user.item2
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getItem2() {
        return item2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.item2
     *
     * @param item2 the value for pu_sys_user.item2
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setItem2(String item2) {
        this.item2 = item2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.item3
     *
     * @return the value of pu_sys_user.item3
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getItem3() {
        return item3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.item3
     *
     * @param item3 the value for pu_sys_user.item3
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setItem3(String item3) {
        this.item3 = item3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pu_sys_user.item4
     *
     * @return the value of pu_sys_user.item4
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public String getItem4() {
        return item4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pu_sys_user.item4
     *
     * @param item4 the value for pu_sys_user.item4
     *
     * @abatorgenerated Thu Feb 25 13:05:56 CST 2016
     */
    public void setItem4(String item4) {
        this.item4 = item4;
    }
}